name: Test
on:
  workflow_call:
    inputs:
      filter:
        description: Filter to apply when running tests
        required: true
        type: string

      solution:
        description: Solution containing test projects
        required: false
        type: string

      ssm-parameter-paths:
        description: Paths to retrieve parameters by. Subsequent paths should be comma delimited
        required: false
        type: string

    secrets:
      github-token:
        description: secrets.BUILD_GITHUB_TOKEN
        required: true
      sonar-token:
        description: secrets.SONAR_TOKEN
        required: true
      aws-access-key-id:
        description: secrets.BUILD_AWS_ACCESS_KEY_ID
        required: false
      aws-secret-access-key:
        description: secrets.BUILD_AWS_SECRET_ACCESS_KEY
        required: false
      aws-role-to-assume:
        description: secrets.OCKERS_BUILD_ROLE
        required: false

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.github-token }}
      GITHUB_USERNAME: GitHub
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - uses: actions/checkout@v3

      - name: Cache SonarCloud Packages
        uses: actions/cache@v3
        with:
          path: ~/sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarCloud Scanner
        id: cache-sonar-scanner
        uses: actions/cache@v3
        with:
          path: ./.sonar/scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          New-Item -Path ./.sonar/scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path ./.sonar/scanner

      - name: Start Sonar Scanner
        shell: pwsh
        run: |
          $key = "${{ github.repository }}".Replace("/", "_")

          .\.sonar\scanner\dotnet-sonarscanner begin `
            /o:orthofi `
            /k:$key `
            /d:sonar.host.url=https://sonarcloud.io `
            /d:sonar.cs.opencover.reportsPaths=artifacts/**/*.xml `
            /d:sonar.login="${{ secrets.sonar-token }}"

      - name: Login to AWS
        if: ${{ inputs.ssm-parameter-paths }}
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key}}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.aws-role-to-assume }}

      - name: Get Parameters
        if: ${{ inputs.ssm-parameter-paths }}
        id: ssm-parameter
        uses: orthofi/actions-aws-ssm-get-by-path@v1
        with:
          paths: ${{ inputs.ssm-parameter-paths }}
          save-to-environment: true
          recursive: true
          decrypt: true
          prefix: OFI__
          delimiter: __

      - name: Test
        env:
          SONAR_TOKEN: ${{ secrets.sonar-token }}
        shell: pwsh
        run: |
          dotnet test ${{ inputs.solution }} -v q -c Release --nologo --filter ${{ inputs.filter }} -r artifacts --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

      - name: Stop Sonar Scanner
        shell: pwsh
        if: always()
        run: |
          .\.sonar\scanner\dotnet-sonarscanner end `
            /d:sonar.login="${{ secrets.sonar-token }}"
