name: Test
on:
  workflow_call:
    inputs:
      filter:
        description: Filter to apply when running tests
        required: true
        type: string

      solution:
        description: Solution containing test projects
        required: false
        type: string

      ssm-parameter-paths:
        description: Paths to retrieve parameters by. Subsequent paths should be comma delimited
        required: false
        type: string

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.BUILD_GITHUB_TOKEN }}
      GITHUB_USERNAME: GitHub
    steps:
      - uses: actions/checkout@v4

      - name: Login to AWS
        if: ${{ inputs.ssm-parameter-paths }}
        uses: aws-actions/configure-aws-credentials@v4.0.0
        with:
          aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.OCKERS_BUILD_ROLE }}

      - name: Get Parameters
        if: ${{ inputs.ssm-parameter-paths }}
        id: ssm-parameter
        uses: orthofi/actions-aws-ssm-get-by-path@v1
        with:
          paths: ${{ inputs.ssm-parameter-paths }}
          save-to-environment: true
          recursive: true
          decrypt: true
          prefix: OFI__
          delimiter: __

      - name: Test
        env:
          OFI__LAUNCH_DARKLY__SDK_KEY: ${{ secrets.LAUNCHDARKLY_DEV_SDK_KEY }}
        shell: pwsh
        run: |
          dotnet test ${{ inputs.solution }} -v q -c Release --nologo --filter ${{ inputs.filter }} --results-directory artifacts --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover

