name: Test
on:
  workflow_call:
    inputs:
      filter:
        description: Filter to apply when running tests
        required: true
        type: string

    secrets:
      github-token:
        description: secrets.BUILD_GITHUB_TOKEN
        required: true

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: dotnet test -c Release --nologo --filter ${{ inputs.filter }} -r artifacts --collect:"XPlat Code Coverage"
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
          GITHUB_USERNAME: foo

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: tests
          path: artifacts
